server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          instance: gateway
          __path__: /var/log/nginx/*log

  - job_name: core-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: api
          instance: core
          __path__: /var/lib/docker/containers/*core-app-service*/*.log

  - job_name: core-app-ro1
    static_configs:
      - targets:
          - localhost
        labels:
          job: api
          instance: ro1
          __path__: /var/lib/docker/containers/*core-app-service-ro1*/*.log

  - job_name: core-app-ro2
    static_configs:
      - targets:
          - localhost
        labels:
          job: api
          instance: ro2
          __path__: /var/lib/docker/containers/*core-app-service-ro2*/*.log

