server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'log_stream'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_logging']
        regex: 'promtail'
        action: keep
      - source_labels: ['__meta_docker_container_label_logging_job']
        target_label: 'job'
      - source_labels: ['__meta_docker_container_label_logging_instance']
        target_label: 'instance'


  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          instance: gateway
          __path__: /var/log/nginx/*log

  - job_name: core-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: api
          instance: core
          __path__: /var/lib/docker/containers/*core-app-service*/*.log

  - job_name: core-app-ro1
    static_configs:
      - targets:
          - localhost
        labels:
          job: api
          instance: ro1
          __path__: /var/lib/docker/containers/*core-app-service-ro1*/*.log

  - job_name: core-app-ro2
    static_configs:
      - targets:
          - localhost
        labels:
          job: api
          instance: ro2
          __path__: /var/lib/docker/containers/*core-app-service-ro2*/*.log

  - job_name: auth-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: api
          instance: auth
          __path__: /var/lib/docker/containers/*app-auth-service*/*.log

  - job_name: auth-app-1
    static_configs:
      - targets:
          - localhost
        labels:
          job: api
          instance: auth-1
          __path__: /var/lib/docker/containers/*app-auth-service-1*/*.log

  - job_name: auth-app-2
    static_configs:
      - targets:
          - localhost
        labels:
          job: api
          instance: auth-2
          __path__: /var/lib/docker/containers/*app-auth-service-2*/*.log
